services:  
  php:
    image: php:8.3-fpm
    container_name: php
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./..:/var/www/html
    # environment:
    #   PHP_MEMORY_LIMIT: 512M
    #   PHP_UPLOAD_MAX_FILESIZE: 50M
    #   PHP_POST_MAX_SIZE: 50M
